version: '2'

services:
  php:
    image: php:7.1-cli-alpine
    volumes:
      - ../:/app
    working_dir: /app

  composer:
    image: composer:1.5
    volumes:
      - ../:/app
    working_dir: /app